project_id = "zbqqfdjfqymallomwtfc"

[functions.fetch-technical-data]
verify_jwt = false

[functions.fetch-option-data]
verify_jwt = false

[functions.fetch-market-indices]
verify_jwt = false

[functions.fetch-market-analysis]
verify_jwt = false

[functions.fetch-live-chart-data]
verify_jwt = false

[functions.fetch-holiday-calendar]
verify_jwt = false

[functions.fetch-global-market]
verify_jwt = false

[functions.fetch-fii-dii-data]
verify_jwt = false

[functions.fetch-economic-calendar]
verify_jwt = false
